# for a list of available software on the different virtual environments, please see:
# https://github.com/actions/virtual-environments/tree/main/images

name: workflow ci
on: [push, pull_request]

env:
  RETENTION_DAYS: 15

jobs:

  #simple test
  hello_world:
    name: hello_world
    runs-on: windows-latest
    steps:
      - name: yak
        run: |
            curl https://files.mcneel.com/yak/tools/latest/yak.exe -o yak.exe
            ./yak search camera