# for a list of available software on the different virtual environments, please see:
# https://github.com/actions/virtual-environments/tree/main/images

name: workflow release
on: [workflow_dispatch]

env:
  RETENTION_DAYS: 15

jobs:

  #simple test
  hello_world:
    name: hello_world
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: |
            echo "Hello World!"