# for a list of available software on the different virtual environments, please see:
# https://github.com/actions/virtual-environments/tree/main/images

name: workflow release
on: [workflow_dispatch]

env:
  RETENTION_DAYS: 15

jobs:

  #simple test
  hello_world:
    name: hello_world
    runs-on: ubuntu-latest
    environment: Yak
    steps:
      - name: say hi
        run: |
            echo "Hello World!"
            if [ -z "${YAK_TOKEN}" ]; then
              echo "YAK_TOKEN not set or empty"
              exit 1
            else
              echo "YAK_TOKEN set and not empty"
            fi