# for a list of available software on the different virtual environments, please see:
# https://github.com/actions/virtual-environments/tree/main/images

name: workflow release
on: [workflow_dispatch]

env:
  RETENTION_DAYS: 15

jobs:

  #pushes the yak package to artifacts
  release:
    name: release
    runs-on: windows-latest
    environment: yak_deploy
    env:
      YAK_TOKEN: ${{ secrets.YAK_TOKEN }}
    steps:
      - name: check yak token
        run: |
            echo "Hello World!"
            if [ -z "${YAK_TOKEN}" ]; then
              echo "YAK_TOKEN not set or empty"
              exit 1
            else
              echo "YAK_TOKEN set and not empty"
            fi
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: get package file name
        run: |
          cd samples/part3/project/build/rh8/
          FILE=$(ls *.yak| head -1)
          echo "YakFile=$FILE" >> $GITHUB_ENV
          echo $FILE
      - name: push to yak
        run: |
            curl https://files.mcneel.com/yak/tools/latest/yak.exe -o yak.exe
            ./yak push ${{env.YakFile}}
      - name: artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          path: samples/part3/project/build/rh8/*.yak
          name: ${{env.YakFile}}
          retention-days: ${{ env.RETENTION_DAYS }}